[[section-building-block-view]]


== Building Block View

=== Level 1 Diagram

Motivation::

This diagram is motivated by the need of having a clear separation of the composition of the application.

[plantuml,"Deployment diagram",png]
----
@startuml

header Architecture of the application
title Architecture of the application

agent "View"
agent "Controller"
agent "Model"
agent "Service layer"
agent "Persistance layer"

"Model" -> "Service layer"
"Controller" -> "Model"
"View" -> "Controller"
"Service layer" -> "Persistance layer"
@enduml
----

Contained Building Blocks::

As seen, the different components are the following:

* *View layer*: The view layer is composed of those elements that the client will interact with; for instance, it includes HTML files, CSS sheets and client-side code.

* *Controller layer*: The controller layer will ensure a proper communication the client and the server.

* *Service layer*: The service layer will be the controller layer's access point to persistent storage (_i.e._, the user's pod and the main database). It will differentiate between the user's pod and the main database.

* *Persistance layer*: The persistance layer will handle data retrieval and persistence logic.

* *Model layer*: The model layer will handle the main logic of the application. 

Important Interfaces::
No important interfaces can be described in this preliminar version of the documentation.


==== View layer

===== Purpose/responsability

As already explained this layer will be composed of those components that the user will interact with.

===== Interfaces

No interfaces have been defined yet.

===== Open Issues/Problems/Risks

No issues, problems or risks are known.

==== Controller layer

===== Purpose/responsability

The controller layer will handle internal communication between the view and the rest of the application.

===== Interfaces

No interfaces have been defined yet.

===== Open Issues/Problems/Risks

No issues, problems or risks are known.

==== Service layer

===== Purpose/responsability

The service layer will handle communication with the persistence layer.

===== Interfaces

No interfaces have been defined yet.

===== Open Issues/Problems/Risks

It is important to consider how we will handle communication between the server and the pods, and if there will be any difference to communicating with the database.

==== Model layer

===== Purpose/responsability

The model layer will handle internal logic.

===== Interfaces

No interfaces have been defined yet.

===== Open Issues/Problems/Risks

No issues, problems or risks are known.

=== Level 2

==== Persistence layer

Currently, the only layer we have somewhat structured is the persistance layer. 

[plantuml,"Deployment diagram",png]
----
@startuml

header Structure of the persistence layer
title Structure of the persistence layer

folder "Persistence layer"{
agent Database
agent "User pod"
}
agent "Service layer"
Database <-- "Service layer"
"User pod" <-- "Service layer"
@enduml
----

As you can see, it is divided in in several two components: the pods and the database.

* The pods will store the user data.
* The database.

What the database will store and what will also be included in the pods is yet to be decided, as we are trying to reach a compromise between storing mostly everything in the pods (which will significantly harm performance) and storing mostly everything in the database (which will harm privacy and does not follow SOLID).