[[section-building-block-view]]


== Building Block View

=== Level 1 Diagram

Motivation::

This diagram is motivated by the need of having a clear separation of the composition of the application.

[plantuml,"BuildingBlockView", png]
----
@startuml

header Architecture of the application
title Architecture of the application

rectangle webapp/src/ {
    agent "View"
}

rectangle restapi/ {
    agent "Controller"
}

"View" -> "Controller"
@enduml
----

Contained Building Blocks::

As seen, the different components are the following:

* *View*: The view layer is composed of those elements that the client will interact with; it includes the React code, CSS sheets and the client-side code.

* *Controller*: The controller layer will ensure a proper communication the client and the server. It currently handles also persistence.

==== View layer

===== Purpose/responsability

As already explained this layer will be composed of those components that the user will interact with.

===== Interfaces

Since we are not using interfaces, we will be seeing important components:

* *The main UI*: It is divided in several components: the left bar, the navbar and the rightbar, each one with its one subfolder in _/webapp/src/components_.

* *The pages*: These are the React components that compose the web. They can be found in _/webapp/src/pages_, in their own folder.

===== Open Issues/Problems/Risks

* The functionality to see friends is yet to be implemented. This one issue is transversal to the application.

==== Controller layer

===== Purpose/responsability

The controller layer will handle internal communication between the view and the rest of the application.

===== Interfaces

* *The controllers*: they handle the logic and the persistence of the application. They can be found in the _restapi_ folder.

===== Open Issues/Problems/Risks

No issues, problems or risks are known.