[[section-deployment-view]]


== Deployment View

=== Infrastructure Level 1

Given that we currently do not know much about hosting the application, at this moment we will follow a simple approach that will likely change in the future.

[plantuml,"Deployment diagram",png]
----
@startuml

header Deployment view
title Deployment view

folder "LoMap server" {
    agent "LoMap Platform"
    database "Database server"
}
agent Pod1
agent Pod2
agent Pod3
agent PodN

Pod1 ---> "LoMap Platform"
Pod1 <--- "LoMap Platform"
Pod2 ---> "LoMap Platform"
Pod2 <--- "LoMap Platform"
Pod3 ---> "LoMap Platform"
Pod3 <--- "LoMap Platform"
PodN ---> "LoMap Platform"
PodN <--- "LoMap Platform"

"Database server" -> "LoMap Platform"
"Database server" <- "LoMap Platform"

@enduml
----

Motivation::

This approach is motivated because it is not very complicated, and can be easily changed at later date if necessary.

Quality and/or Performance Features::

This approach has a series of upsides and downsides.

On one hand, its simplicity means it can be deployed easily changed without much changes at a later dater, or even the self-hosted. Placing the database in the same server also means that the server will not have latency, or a very minor one, and that server costs will also be less. On the other, given that we are placing everything inside the same server, it will certainly affect performance and in the case of the server going down, not just the application but also the database will go down.

Nevertheless, the deployment has yet occur and we have not thought how we will do it, beyond this approach.

Mapping of Building Blocks to Infrastructure::

As it can be seen, this approach makes the pods be connected to the platform at nearly all times. Currently, we have discussed that the database will store fixed data that all users will necessarily retrieve, but that may change in the future.

=== Infrastructure Level 2

==== The server

Although we have yet to choose the operating system that will run it, it is probably between Windows Server and Linux. Both come with their own upsides and downsides:

- On one hand, using Windows means we have (usually) a graphical interface we can use, which helps the deploying process. But using Windows means we will have to pay license, and Docker (if we use it) cannot run natively on Windows, only through Hyper-V.

- On the other hand, using Linux means we do not have a graphical interface (though we can install one, it is not usually done). But we are currently focusing mainly on Linux in another subject, and we do not have to pay a license, and Docker can natively run in Linux.

==== The database management system

We have yet to choose a database management system, but we have several options:

- SQL DBMSs are the ones we are most used to, but they may not be a right fit for the application.

- Neo4J is a NoSQL graph database that may be useful when mapping the relationships between users, but it comes with the downside of not having constraints, and being limited in its Community edition. This last limitation can be overcome by using another graph database, though we have the risk of being not used to it.

- MongoDB is another NoSQL database that uses JSON documents, but only one of our members is used to it, so it may not be the right fit, as we run the risk of incurring in technical debt. See that part for more information.
