[[section-deployment-view]]


== Deployment View

=== Infrastructure Level 1

[plantuml,"Deployment diagram",png, id = "DeployDiagramView"]
----
@startuml
header Deployment view
title Deployment view

agent "LoMap server"
agent "OpenStreetMaps"
database "Database server"
agent Pod1
agent Pod2
agent Pod3

Pod1 <--> "LoMap server"
"LoMap server" <--> Pod2
PodN <--> "LoMap server"
"LoMap server" <-> "Pod3"

"MongoDB Database" <-> "LoMap server"
"OpenStreetMaps" -> "LoMap server"

@enduml
----

Motivation::

This approach is motivated because it is not very complicated, and can be easily changed at later date if necessary. It also removes the dependency in the same machine of the database and the server, so if one is down, we can launch it in another system so long we change the machine hosting one service or the other. We are also depending on an external provider, that being OpenStreetMaps, to supply the map we need for the application to work, so the will run so long OpenStreetMaps does work.

Quality and/or Performance Features::

This approach has a series of upsides and downsides.

On one hand, its simplicity means it can be deployed easily changed without much changes at a later dater. On the other hand, this deployment scheme depends on both servers not being down, and if either or OpenStreetMaps is down, then the application wouldn't properly work. Also, we have to consider that users might have different pod providers (and as much as we'd like to, it simply is not feasible to test the application in every single pod provider), so there's another possible bottleneck there.

Mapping of Building Blocks to Infrastructure::

As it can be seen, this approach makes the pods be connected to the platform at nearly all times. Currently, we have discussed that the database will store fixed data that all users will necessarily retrieve, but that may change in the future, as a common data schema has yet to be defined with the rest of the implementations.

=== Infrastructure Level 2

==== The server

Although we have yet to choose the operating system that will run it, it will probably run on Linux. On the one hand, using Linux means we do not have a graphical interface but if we consider necessary we can install.

==== The database management system

We have chosen to use MongoDB. This decision was considered due to the experience of one member of the group using MongoDB through Mongoose, as well as using Typescript to run the product and, thus being posible to manipulate the data directly.