[[section-concepts]]
== Cross-cutting Concepts
Some cross-cutting concepts of the system will be detailed here. These can give a broader look of our application

=== Domain model
Users can have several friends as well as having added several reviews or landmarks.
In addition, landmarks will have reviews associated to them and viceversa.

[plantuml,"ConceptsDiagram",png]
----
@startuml
object User{
    id: String
    friends: List<User>
    landmarks: List<Landmark>
    reviews: List<Review>
}

object Landmark{
    id: String
    name: String
    category: String
    description: String
    image: String
    reviews: List<Review>
}

object Review{
    id: String
    landmarkId: String
    rating: int
    comment: String
}

User o--> User
User o--> Landmark
User o--> Review
Landmark o--> Review
@enduml
----

=== Security

This is probably the most important concept of our application. To give users the most safety we only store the information necessary to function and we will store most of it in users' SOLID pods, this means that users will have power over how and with who they share their data.

=== User experience

We want to focus on creating an app that is easy to use and intuitive. Thus, we will follow the global standards so users know what to do without thinking too much. Some of these are having menus on a side, using similar colors as other map applications...

=== Architectural and design patterns

The application will be based on the MVC architectural style using a N-layer structure. This will make the code clean, easy to change and organised.
